### PR TITLE
change extraction and replace methods to be more consistent to base R

### LINKED ISSUE #176: `[.integer64` performance regression in >=4.5.2
I'm running into an issue where code that ran previously becomes so slow it doesn't finish. I've traced the slowness back to the function `.[integer64` in this package.

https://github.com/r-lib/bit64/blob/62cd4ee84356224feb939632b5d04c802bb72306/R/integer64.R#L886-L905

Or more concretely to this line:
```R
na_idx <- is.na(rep(TRUE, length(x))[i])
```

In my case I have a `duckdb` database I'm using `DBI` to fetch results of a query in batches. In my case `i` is 100k integers and `x` is almost 500 million integer64's. Materializing a vector of size `x` seems to be the issue.  Using tag `4.0.5` does not have this issue while `4.5.2` and later have it. From the changelog it there was a bugfix I think is responsible: ""[.integer64"(x,i) can now cope with i longer than x"

The following code should demonstrate the difference when running with tags `4.0.5` and `4.6.0-1`

```R
# remotes::install_github("r-lib/bit64@4.0.5") or remotes::install_github("r-lib/bit64@4.6.0-1")
library(bit64)
x <- as.integer64(rep(1, 1e8))
i <- sample(c(NA, 1:1e4, 1e7 + 1), size = 1e5, replace = TRUE)
microbenchmark(
  bit64 = x[i],
  times = 10L
)
```

4.0.5:
```Text
Unit: microseconds
  expr     min      lq     mean  median      uq      max neval
 bit64 672.959 894.574 916.0243 945.992 961.139 1027.361    10
```

4.6.0-1:
```Text
Unit: milliseconds
  expr      min       lq     mean   median       uq      max neval
 bit64 194.0301 200.1372 213.4576 204.3696 233.6707 235.2293    10
```

current main:
```Text
Unit: milliseconds
  expr      min       lq     mean  median       uq      max neval
 bit64 193.7276 200.4751 214.2612 205.575 232.2011 238.9536    10
```

Roughly a difference of ~333x. I thought about replacing the offending line with 
```R
 na_idx <- is.na(i) | (i > length(x))
```

But unfortunately that doesn't work when i is boolean and length(i) > length(x)  (untested case btw).

### PR DESCRIPTION
**Pull request by hcirellu**
Closes #176

### CODE REVIEW

File: tests/testthat/test-integer64.R [hunk 1]
```diff
@@ -493,3 +533,236 @@ test_that("match works with zero length input", {
   expect_identical(match(x64, integer(), nomatch=10L), match(x32, integer(), nomatch=10L))
   expect_identical(match(integer(), x64), match(integer(), x32))
 })
+
+
+test_that("extraction and replacement works consistent to integer (except for double)", {
+
+  skip_if_not_r_version("4.0.0")
```
Comment (MichaelChirico) [inline tests/testthat/test-integer64.R]: See #200

```suggestion
  skip_unless_r(">= 4.0.0")
```

File: tests/testthat/test-integer64.R [hunk 2]
```diff
@@ -493,3 +533,236 @@ test_that("match works with zero length input", {
...
+  sel = c(TRUE, FALSE, NA, TRUE)
+  expect_identical(y[sel], structure(as.integer64(x[sel]), names=names(x)[sel]))
+  sel = c(1, NA, 3, 11)
+  expect_identical(y[sel], structure(as.integer64(x[sel]), names=names(x)[sel]))
+  expect_identical(y[as.integer64(sel)], structure(as.integer64(x[sel]), names=names(x)[sel]))
+  sel = c(-1, -3, 0, -11)
+  expect_identical(y[sel], structure(as.integer64(x[sel]), names=names(x)[sel]))
+  sel = c(-1, -3, 0, -11, NA)
+  expect_error(x[sel], "only 0's may be mixed with negative subscripts", fixed=TRUE)
+  expect_error(y[sel], "only 0's may be mixed with negative subscripts", fixed=TRUE)
```
Comment (MichaelChirico) [inline tests/testthat/test-integer64.R]: this only uses base R code, so it leaves us vulnerable to tests breaking when nothing in our own package changes (unlikely though it may be).

Is the intent here to test that both `x[sel]` and `y[sel]` have identical error messages? Maybe something like this is preferable then?

```suggestion
  expect_identical(
    tryCatch(x[sel], error=conditionMessage),
    tryCatch(y[sel], error=conditionMessage)
  )
```

File: tests/testthat/test-integer64.R [hunk 3]
```diff
@@ -493,3 +533,236 @@ test_that("match works with zero length input", {
...
+
+  expect_identical(as.integer64(c("9218868437227407266", "1"))[c(1,NA,3,4)], structure(as.integer64(c("9218868437227407266", NA_character_, NA_character_, NA_character_))))
+
+  sel = c("d", "", "b", NA_character_)
+  expect_identical(y[sel], structure(as.integer64(x[sel]), names=names(x)[match(sel, names(x))]))
+
+  m32 = matrix(1:10, nrow=2L)
```
Comment (MichaelChirico) [inline tests/testthat/test-integer64.R]:
```suggestion
})

test_that("extraction and replacement works consistent to integer (matrices; except for double)", {
  m32 = matrix(1:10, nrow=2L)
```

File: tests/testthat/test-integer64.R [hunk 4]
```diff
@@ -493,3 +533,236 @@ test_that("match works with zero length input", {
...
+  expect_identical(m32[integer(), 1:2, drop=FALSE], structure(integer(), dim = c(0L, 2L)))
+  expect_identical(m64[integer(), 1:2, drop=FALSE], structure(integer64(), dim = c(0L, 2L)))
+
+  expect_identical(m32[1:2, integer(), drop=FALSE], structure(integer(), dim = c(2L, 0L)))
+  expect_identical(m64[1:2, integer(), drop=FALSE], structure(integer64(), dim = c(2L, 0L)))
+
+  expect_identical(m32[1:2, 1:3, drop=TRUE], structure(as.integer(1:6), dim = c(2L, 3L)))
+  expect_identical(m64[1:2, 1:3, drop=TRUE], structure(as.integer64(1:6), dim = c(2L, 3L)))
+
+  expect_identical(m32[1:2], structure(as.integer(1:2)))
```
Comment (MichaelChirico) [inline tests/testthat/test-integer64.R]: remove the `structure()` calls?

also `as.integer()` for `a:b` which is always `integer`?

File: R/integer64.R [hunk 5]
```diff
@@ -821,92 +822,158 @@ str.integer64 <- function(object,
...
-      if (length(na_idx))
-        ret[na_idx] <- NA_integer64_
-    } else {
-      na_idx <- is.na(rep(TRUE, length(x))[i])
-      if (any(na_idx))
-        ret[na_idx] <- NA_integer64_
+#' @rdname extract.replace.integer64
+#' @export
+`[.integer64` = function(x, i, j, ..., drop=TRUE) {
+  args = lapply(as.list(sys.call())[-(1:2)], {function(el) {
```
Comment (MichaelChirico) [inline R/integer64.R]: is the `{` before `function` doing something?

File: tests/testthat/test-integer64.R [hunk 6]
```diff
@@ -222,21 +222,58 @@ test_that("S3 class basics work", {
...
+
+  x = as.integer64(1:10)
+  x[[1.0]] = 3L
+  x[[2L]] = 4.0 + 0.0i
+  expect_identical(x, as.complex(c(3:4, 3:10)))
+  
+  x = as.integer64(1:10)
+  x[[1.0]] = 3L
+  x[[2L]] = "4"
+  expect_identical(x, as.character(c(3:4, 3:10)))
```
Comment (MichaelChirico) [inline tests/testthat/test-integer64.R]: ditto w.r.t. concerns about breaking change

File: tests/testthat/test-integer64.R [hunk 7]
```diff
@@ -818,3 +855,273 @@ test_that("match works with zero length input", {
   expect_identical(match(x64, integer(), nomatch=10L), match(x32, integer(), nomatch=10L))
   expect_identical(match(integer(), x64), match(integer(), x32))
 })
+
+
+test_that("extraction and replacement works consistent to integer (vectors; except for double)", {
+
+  skip_unless_r(">= 4.0.0")
```
Comment (MichaelChirico) [inline tests/testthat/test-integer64.R]: why do we need R 4 here?

File: tests/testthat/test-integer64.R [hunk 8]
```diff
@@ -222,21 +222,58 @@ test_that("S3 class basics work", {
...
+
+  x = as.integer64(1:10)
+  x[1.0] = 2L
+  x[2L] = 3.0 + 0.0i
+  expect_identical(x, as.complex(c(2:3, 3:10)))
+  
+  x = as.integer64(1:10)
+  x[1.0] = 2L
+  x[2L] = "3"
+  expect_identical(x, as.character(c(2:3, 3:10)))
```
[the remark this answers is not in the document]
Comment (hcirellu) [reply tests/testthat/test-integer64.R]: I'll propose something.

[the remark this answers is not in the document]
Comment (hcirellu) [reply tests/testthat/test-integer64.R]: Would this be ok?
```
x64 <- as.integer64(1:10)
x64[1] <- "1"
# warning:
# In `[<-.integer64`(`*tmp*`, 1, value = "1") :
#  The assignment of character values to integer64 vectors and matrices with automatic coercion to integer64 is deprecated and will be changed to a more R consistent behaviour of coercing to character in future versions of bit64. If you wish you can update your code to the new behaviour by setting the option 'bit64.promoteInteger64ToCharacter' to TRUE.
```
Or how do you handle that usually?

[the remark this answers is not in the document]
Comment (hcirellu) [reply tests/testthat/test-integer64.R]: I added something. I hope that meets the expectations.
If so, I think a news entry needs to be added.

File: R/integer64.R [hunk 9]
```diff
@@ -912,53 +913,137 @@ str.integer64 = function(object, vec.len=strO$vec.len, give.head=TRUE, give.leng
...
+      } else if (is.character(arg1Value)) {
+        ret[is.na(arg1Value) | arg1Value == "" | !arg1Value %in% names(x)] = NA_integer64_real
+      } else if (anyNA(arg1Value) || suppressWarnings(max(arg1Value, na.rm=TRUE)) > length(x)) {
+        arg1Value = arg1Value[arg1Value != 0]
+        ret[which(is.na(arg1Value) | arg1Value > length(x))] = NA_integer64_real
+      }
+    }
+  } else {
+    # array/matrix mode
+    dimSelect = args[seq_along(dim(x))]
```
Comment (MichaelChirico) [inline R/integer64.R]: is there an implication of using `dim(ret)` above but `dim(x)` here?

File: R/integer64.R [hunk 10]
```diff
@@ -912,53 +913,137 @@ str.integer64 = function(object, vec.len=strO$vec.len, give.head=TRUE, give.leng
...
+
+  # NA handling
+  if (length(dim(ret)) <= 1L) {
+    # vector mode
+    if (!is.symbol(args[[1L]]) || args[[1L]] != substitute()) {
+      arg1Value = args[[1L]]
+      if (is.logical(arg1Value)) {
+        ret[is.na(arg1Value[arg1Value])] = NA_integer64_real
+      } else if (is.character(arg1Value)) {
+        ret[is.na(arg1Value) | arg1Value == "" | !arg1Value %in% names(x)] = NA_integer64_real
```
Comment (MichaelChirico) [inline R/integer64.R]: TIL `x[""]` won't select an element named `""` 😲

File: R/integer64.R [hunk 11]
```diff
@@ -912,53 +913,137 @@ str.integer64 = function(object, vec.len=strO$vec.len, give.head=TRUE, give.leng
...
+  })
+  
+  # TODO(#44): next Release: change default behavior; subsequent Release: change from message to warning; subsequent Release: change from warning to error; subsequent Release: remove option and promote_to_char
+  if (is.character(value) && !(promote_to_char <- isTRUE(getOption("bit64.promoteInteger64ToCharacter", FALSE))))
+    if (!isTRUE(getOption("bit64.suppressPromoteInteger64ToCharacterMessage", FALSE))) {
+      message(.bit64.suppressPromoteInteger64ToCharacterMessage, "\nBy setting the option 'bit64.suppressPromoteInteger64ToCharacterMessage' to TRUE the display of this message can be suppressed. (This message is only displayed once per session.)")
+      options(bit64.suppressPromoteInteger64ToCharacterMessage=TRUE)
+    }
+  
+  if (is.character(value) && promote_to_char || is.complex(value) || (is.double(value) && class(value)[1L] != "numeric")) {
```
Comment (MichaelChirico) [inline R/integer64.R]: nit: I prefer using `()` to make precedence of `&&` vs. `||` clear (I can never remember & it's a common source of mistakes)

File: R/zzz.R [hunk 12]
```diff
@@ -22,7 +22,16 @@ if (getRversion() < "3.6.0") {
     obj
   }
 }
-  
+
+
+options(bit64.suppressPromoteInteger64ToCharacterMessage=TRUE)
```
Comment (MichaelChirico) [inline R/zzz.R]: could you explain how this is meant to work? it looks unfamiliar to me. The option is set at package build time? maybe it should be in an `.onLoad()` hook instead?

Comment (hcirellu) [reply R/zzz.R]: I want to enforce that the option is set to TRUE on loading the package, such that the `.bit64.suppressPromoteInteger64ToCharacterMessage` message is not displayed if the package is only loaded and not attached. AFAIK this could also be put into the `.onLoad()` hook  with the same result. Hence I saved some lines of code.

The idea is to suppress the `.bit64.suppressPromoteInteger64ToCharacterMessage` if the package is only loaded and not attached, e.g. by imports from another package. If someone explicitly attaches the package he/she should be informed about the upcoming changes in the package startup message. If this is not read or suppressed, the user gets another hint the first time a character is implicitly converted to integer64.

**Review by MichaelChirico — COMMENTED** [review]
Basically looks good. I'd still like to revisit how the message & its suppression is issued/not.

OTOH, maybe we can just drop that mechanism? Or we can revisit it in follow-up work? There's an argument that just putting the entry prominently in the NEWS is enough for the next release, where no behavior will yet change.

**Comment by hcirellu** [comment]
> Basically looks good. I'd still like to revisit how the message & its suppression is issued/not.
> 
> OTOH, maybe we can just drop that mechanism? Or we can revisit it in follow-up work? There's an argument that just putting the entry prominently in the NEWS is enough for the next release, where no behavior will yet change.

I removed the `bit64.suppressPromoteInteger64ToCharacterMessage` mechanism and kept the option `bit64.promoteInteger64ToCharacter` to switch to the new behavior, as stated in the startup message.

**Comment by MichaelChirico** [comment]
Thanks, this is great!
