### PR TITLE
Treat '...' like missing() in AST

### LINKED ISSUE #275: Revdep failure: Rdiagnosislist
Observed failure from package examples

```
> ### ** Examples
> 
> SNOMED <- sampleSNOMED()
> 
> TRANSITIVE <- createTransitive('Heart failure')
Error in eval(el, eval_frame) : '...' used in an incorrect context
Calls: createTransitive ... position_args_with_int64_to_int_coercion -> lapply -> FUN -> eval -> eval
Execution halted
```

### PR DESCRIPTION
**Pull request by hcirellu**
This should fix #275.

I added a special handling for symbol `...` in `[.integer64`.

The example in the related issue is added to the tests.

Closes #275

### CODE REVIEW

**Review by MichaelChirico — COMMENTED** [review]
another test case I had in mind is a helper passing ... something like

```r
getter = function(x, ...) x[...]
```

calling that directly and with lapply should work

**Comment by MichaelChirico** [comment]
Great! Let's add it to the test suite

File: R/integer64.R [hunk 1]
```diff
@@ -938,7 +938,7 @@ position_args_with_int64_to_int_coercion = function(sys_call, eval_frame, skipLa
     # array/matrix mode
     dimSelect = args[seq_along(dim(x))]
     for (ii in seq_along(dimSelect)) {
-      if (is.symbol(dimSelect[[ii]]) && dimSelect[[ii]] == substitute()) next
+      if (is.symbol(dimSelect[[ii]]) && (dimSelect[[ii]] == substitute() || dimSelect[[ii]] == as.symbol("..."))) next
```
Comment (MichaelChirico) [inline R/integer64.R]:
```suggestion
      if (identical(dimSelect[[ii]], substitute()) || identical(dimSelect[[ii]], quote(...))) next
```
